// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright (c) 2025 Guilherme Ferrari Brescia

// NeuralSignalTypes.ts
// Interface for neural signal types generated by the language model

import { SymbolicQuery } from '../../types/SymbolicQuery';

/**
 * Represents a symbolic neural signal for the artificial brain model
 * Each signal describes a cognitive core to be activated, its intensity, and the symbolic search target
 */
export interface NeuralSignal {
  /**
   * Cognitive core to be activated
   * - memory: Memory and associative recall (hipocampus)
   * - valence: Emotional polarity and affective intensity (amygdala)
   * - metacognitive: Introspection and reflection (prefrontal cortex)
   * - associative: Associative connections between concepts (association cortex)
   * - language: Language processing (Broca and Wernicke areas)
   * - planning: Planning and strategy (dorsolateral cortex)
   */
  core: string;
  
  /**
   * Intensity of activation of this core (0.0 to 1.0)
   */
  intensity: number;
  
  /**
   * Symbolic query for the cognitive core (what to search for)
   * Can contain the main query and additional metadata
   */
  symbolic_query: SymbolicQuery;

  /**
   * Quantity of memories to be retrieved by the core
   */
  topK?: number;

  /**
   * Pinecone search results for this core
   */
  pineconeResults?: string[];

  /**
   * Symbolic insights pre-analyzed (e.g. "emotion": "anxiety")
   */
  symbolicInsights?: Record<string, unknown>;

  /**
   * Expanded keywords for semantic search
   */
  keywords?: string[];

  /**
   * Additional parameters for neural signal processing
   */
  params?: Record<string, unknown>;

  /**
   * Contextual filters for search
   */
  filters?: Record<string, unknown>;

  /**
   * Indicates if semantic expansion should be applied
   */
  expand?: boolean;
  
  /**
   * Emotional valence of the neural signal
   */
  valence?: string;
  
  /**
   * Score indicating the level of contradiction in the signal (0.0 to 1.0)
   */
  contradictionScore?: number;
  
  /**
   * Score indicating the coherence of the signal (0.0 to 1.0)
   */
  coherence?: number;
  
  /**
   * Patterns detected in the neural signal
   */
  patterns?: string[];
}

/**
 * Response returned by the neural signal generation service
 */
export interface NeuralSignalResponse {
  /**
   * Array of neural signals generated representing the activation of cognitive cores
   */
  signals: NeuralSignal[];
  
  /**
   * High-level analysis of generated signals and symbolic cognitive state
   */
  analysis?: string;
}

/**
 * Represents the result of processing a neural core after memory search
 * and synthesis of relevant information.
 * Used in the neural integration phase.
 */
export interface NeuralProcessingResult {
  /**
   * Núcleo cognitivo that was activated (e.g. 'memory', 'valence')
   */
  core: string;
  
  /**
   * Intensity of activation of this core (0.0 to 1.0)
   */
  intensity: number;
  
  /**
   * Consolidated textual output of this core processing
   */
  output: string;
  
  /**
   * Symbolic insights extracted and structured
   */
  insights: Record<string, unknown>;
}
